function filename = genFilename(resultsFolder, dim, obsType, coverage,...
    samp, plan, saveFlag)

if obsType == 1
    obsDesc = num2str(round(coverage*100));
    filename = [resultsFolder,'/fmtResults_dim',num2str(dim),'_obs',...
        num2str(obsType),'_cov',obsDesc,'_sample',num2str(samp),'_plan',...
        num2str(plan),'_',num2str(saveFlag),'.csv'];
else
    filename = [resultsFolder,'/fmtResults_dim',num2str(dim),'_obs',...
        num2str(obsType),'_sample',num2str(samp),'_plan',...
        num2str(plan),'_',num2str(saveFlag),'.csv'];
end
    
end